name: Terraform fmt

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'The version of Terraform to use'
        required: false
        default: '1.9.0'
        type: string

  workflow_dispatch:

jobs:
  verify:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Run Terraform fmt
      run: terraform fmt -recursive

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git add -A && git commit -m "Apply terraform fmt")

    - name: Push changes
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        git pull origin HEAD:$BRANCH_NAME
        git push origin HEAD:$BRANCH_NAME