# name: 'Terraform-Docs'

# on:
#   pull_request:
#     branches:
#     - main
#   workflow_call:

# env:
#   TF_LOG: INFO

# jobs:
#     docs:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v3
#           with:
#             ref: ${{ github.sha }}
#             fetch-depth: '0'
    
#         - name: Render terraform docs inside the README.md and push changes back to PR branch
#           uses: terraform-docs/gh-actions@v1.0.0
#           with:
#             working-dir: .
#             output-file: README.md
#             output-method: inject
#             git-push: "true"


name: Org Terraform Docs
on:
    pull_request:

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-docs.yml@main